FROM rust:1.76 as builder
ARG SERVICE

WORKDIR /usr/src/app
COPY . .

# Build only the specified service
RUN cargo build --release --package ${SERVICE}

FROM debian:bookworm-slim
ARG SERVICE
RUN apt-get update && apt-get install -y libssl-dev ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local/bin
COPY --from=builder /usr/src/app/target/release/${SERVICE} /usr/local/bin/app

CMD ["app"]
